### ISSUE TITLE
Image Validation

### ISSUE THREAD

**Issue by AmnaMansha** [Majid-Razzaq/react-blog-frontend#2]
The image upload section handles errors on the server side but does not verify the file type or size on the client side before submission. This might lead to an error if the server rejects invalid image files, such as unsupported formats or files that are too large. Adding file validation would improve the user experience by providing instant feedback.

**Comment by Majid-Razzaq** [comment]
Hi,
I have added validations for image uploads directly in the backend within the Laravel controller. This includes checks for file extensions like jpg, jpeg and file size limits.

**Comment by AmnaMansha** [comment]
yes that is what i am asking for you you handled every thing on server side how the user knows about the error you have to handle and popup exact message in the frontend also.
